[project]
name = "opsdiag-client"
version = "0.7.0"
description = "Add your description here"
authors = [
    { name = "csunny", email = "cfqcsunny@gmail.com" }
]
license = "MIT"
readme = "README.md"
requires-python = ">= 3.10"

dependencies = ["opsdiag-serve"]

[project.urls]
Homepage = "https://github.com/opsdiag-ai/opsdiag"
Documentation = "http://docs.opsdiag.ai/docs/overview"
Repository = "https://github.com/opsdiag-ai/opsdiag.git"
Issues = "https://github.com/opsdiag-ai/opsdiag/issues"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv]
managed = true
dev-dependencies = []

[tool.hatch.build.targets.wheel]
packages = ["src/opsdiag_client"]
exclude = [
    "src/opsdiag_client/**/tests",
    "src/opsdiag_client/**/tests/*",
    "src/opsdiag_client/tests",
    "src/opsdiag_client/tests/*",
    "src/opsdiag_client/**/examples",
    "src/opsdiag_client/**/examples/*"
]