"""New migration

Revision ID: 34af3fe9a4fb
Revises: ff1d257f4bed
Create Date: 2025-09-05 15:38:59.687504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34af3fe9a4fb'
down_revision: Union[str, None] = 'ff1d257f4bed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
