"""New migration

Revision ID: 7c0482c8595a
Revises: 127956df0b5a
Create Date: 2025-09-07 20:46:41.397564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c0482c8595a'
down_revision: Union[str, None] = '127956df0b5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('derisk_serve_mcp')
    with op.batch_alter_table('derisk_serve_variables', schema=None) as batch_op:
        batch_op.drop_index('ix_derisk_serve_variables_key_info')
        batch_op.drop_index('ix_derisk_serve_variables_name')
        batch_op.drop_index('ix_derisk_serve_variables_sys_code')
        batch_op.drop_index('ix_derisk_serve_variables_user_name')

    op.drop_table('derisk_serve_variables')
    with op.batch_alter_table('derisk_serve_flow', schema=None) as batch_op:
        batch_op.drop_index('ix_derisk_serve_flow_dag_id')
        batch_op.drop_index('ix_derisk_serve_flow_name')
        batch_op.drop_index('ix_derisk_serve_flow_sys_code')
        batch_op.drop_index('ix_derisk_serve_flow_uid')
        batch_op.drop_index('ix_derisk_serve_flow_user_name')

    op.drop_table('derisk_serve_flow')
    with op.batch_alter_table('derisk_serve_model', schema=None) as batch_op:
        batch_op.drop_index('ix_derisk_serve_model_sys_code')
        batch_op.drop_index('ix_derisk_serve_model_user_name')

    op.drop_table('derisk_serve_model')
    with op.batch_alter_table('derisk_serve_file', schema=None) as batch_op:
        batch_op.drop_index('ix_derisk_serve_file_sys_code')
        batch_op.drop_index('ix_derisk_serve_file_user_name')

    op.drop_table('derisk_serve_file')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('derisk_serve_file',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('bucket', sa.VARCHAR(length=255), nullable=False),
    sa.Column('file_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('file_name', sa.VARCHAR(length=256), nullable=False),
    sa.Column('file_size', sa.INTEGER(), nullable=True),
    sa.Column('storage_type', sa.VARCHAR(length=32), nullable=False),
    sa.Column('storage_path', sa.VARCHAR(length=512), nullable=False),
    sa.Column('uri', sa.VARCHAR(length=512), nullable=False),
    sa.Column('custom_metadata', sa.TEXT(), nullable=True),
    sa.Column('file_hash', sa.VARCHAR(length=128), nullable=True),
    sa.Column('user_name', sa.VARCHAR(length=128), nullable=True),
    sa.Column('sys_code', sa.VARCHAR(length=128), nullable=True),
    sa.Column('gmt_create', sa.DATETIME(), nullable=True),
    sa.Column('gmt_modified', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bucket', 'file_id', name='uk_bucket_file_id')
    )
    with op.batch_alter_table('derisk_serve_file', schema=None) as batch_op:
        batch_op.create_index('ix_derisk_serve_file_user_name', ['user_name'], unique=False)
        batch_op.create_index('ix_derisk_serve_file_sys_code', ['sys_code'], unique=False)

    op.create_table('derisk_serve_model',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('host', sa.VARCHAR(length=255), nullable=False),
    sa.Column('port', sa.INTEGER(), nullable=False),
    sa.Column('model', sa.VARCHAR(length=255), nullable=False),
    sa.Column('provider', sa.VARCHAR(length=255), nullable=False),
    sa.Column('worker_type', sa.VARCHAR(length=255), nullable=False),
    sa.Column('params', sa.TEXT(), nullable=False),
    sa.Column('enabled', sa.INTEGER(), nullable=True),
    sa.Column('worker_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('user_name', sa.VARCHAR(length=128), nullable=True),
    sa.Column('sys_code', sa.VARCHAR(length=128), nullable=True),
    sa.Column('gmt_create', sa.DATETIME(), nullable=True),
    sa.Column('gmt_modified', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model', 'provider', 'worker_type', name='uk_model_provider_type')
    )
    with op.batch_alter_table('derisk_serve_model', schema=None) as batch_op:
        batch_op.create_index('ix_derisk_serve_model_user_name', ['user_name'], unique=False)
        batch_op.create_index('ix_derisk_serve_model_sys_code', ['sys_code'], unique=False)

    op.create_table('derisk_serve_flow',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('uid', sa.VARCHAR(length=128), nullable=False),
    sa.Column('dag_id', sa.VARCHAR(length=128), nullable=True),
    sa.Column('label_info', sa.VARCHAR(length=128), nullable=True),
    sa.Column('name', sa.VARCHAR(length=128), nullable=True),
    sa.Column('flow_category', sa.VARCHAR(length=64), nullable=True),
    sa.Column('flow_data', sa.TEXT(), nullable=True),
    sa.Column('description', sa.VARCHAR(length=512), nullable=True),
    sa.Column('state', sa.VARCHAR(length=32), nullable=True),
    sa.Column('error_message', sa.VARCHAR(length=512), nullable=True),
    sa.Column('source', sa.VARCHAR(length=64), nullable=True),
    sa.Column('source_url', sa.VARCHAR(length=512), nullable=True),
    sa.Column('version', sa.VARCHAR(length=32), nullable=True),
    sa.Column('define_type', sa.VARCHAR(length=32), nullable=True),
    sa.Column('editable', sa.INTEGER(), nullable=True),
    sa.Column('variables', sa.TEXT(), nullable=True),
    sa.Column('user_name', sa.VARCHAR(length=128), nullable=True),
    sa.Column('sys_code', sa.VARCHAR(length=128), nullable=True),
    sa.Column('gmt_create', sa.DATETIME(), nullable=True),
    sa.Column('gmt_modified', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uid', name='uk_uid')
    )
    with op.batch_alter_table('derisk_serve_flow', schema=None) as batch_op:
        batch_op.create_index('ix_derisk_serve_flow_user_name', ['user_name'], unique=False)
        batch_op.create_index('ix_derisk_serve_flow_uid', ['uid'], unique=False)
        batch_op.create_index('ix_derisk_serve_flow_sys_code', ['sys_code'], unique=False)
        batch_op.create_index('ix_derisk_serve_flow_name', ['name'], unique=False)
        batch_op.create_index('ix_derisk_serve_flow_dag_id', ['dag_id'], unique=False)

    op.create_table('derisk_serve_variables',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('key_info', sa.VARCHAR(length=128), nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), nullable=True),
    sa.Column('label_info', sa.VARCHAR(length=128), nullable=True),
    sa.Column('value', sa.TEXT(), nullable=True),
    sa.Column('value_type', sa.VARCHAR(length=32), nullable=True),
    sa.Column('category', sa.VARCHAR(length=32), nullable=True),
    sa.Column('encryption_method', sa.VARCHAR(length=32), nullable=True),
    sa.Column('salt', sa.VARCHAR(length=128), nullable=True),
    sa.Column('scope', sa.VARCHAR(length=32), nullable=True),
    sa.Column('scope_key', sa.VARCHAR(length=256), nullable=True),
    sa.Column('enabled', sa.INTEGER(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('user_name', sa.VARCHAR(length=128), nullable=True),
    sa.Column('sys_code', sa.VARCHAR(length=128), nullable=True),
    sa.Column('gmt_create', sa.DATETIME(), nullable=True),
    sa.Column('gmt_modified', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('derisk_serve_variables', schema=None) as batch_op:
        batch_op.create_index('ix_derisk_serve_variables_user_name', ['user_name'], unique=False)
        batch_op.create_index('ix_derisk_serve_variables_sys_code', ['sys_code'], unique=False)
        batch_op.create_index('ix_derisk_serve_variables_name', ['name'], unique=False)
        batch_op.create_index('ix_derisk_serve_variables_key_info', ['key_info'], unique=False)

    op.create_table('derisk_serve_mcp',
    sa.Column('mcp_code', sa.VARCHAR(length=255), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('type', sa.VARCHAR(length=255), nullable=False),
    sa.Column('author', sa.VARCHAR(length=255), nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), nullable=True),
    sa.Column('version', sa.VARCHAR(length=255), nullable=True),
    sa.Column('stdio_cmd', sa.TEXT(), nullable=True),
    sa.Column('sse_url', sa.TEXT(), nullable=True),
    sa.Column('sse_headers', sa.TEXT(length=2147483647), nullable=True),
    sa.Column('token', sa.TEXT(length=2147483647), nullable=True),
    sa.Column('icon', sa.TEXT(), nullable=True),
    sa.Column('category', sa.TEXT(), nullable=True),
    sa.Column('installed', sa.INTEGER(), nullable=True),
    sa.Column('available', sa.BOOLEAN(), nullable=True),
    sa.Column('server_ips', sa.TEXT(), nullable=True),
    sa.Column('gmt_create', sa.DATETIME(), nullable=True),
    sa.Column('gmt_modified', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('mcp_code')
    )
    # ### end Alembic commands ###
