[system]
# 纯对话模式配置 - 禁用知识检索避免调用embedding模型
language = "${env:DERISK_LANG:-zh}"
api_keys = []
encrypt_key = "your_secret_key"

# 禁用知识检索功能
enable_knowledge_retrieval = false

# Server Configurations
[service.web]
host = "0.0.0.0"
port = 8000

[service.web.database]
type = "sqlite"
path = "pilot/meta_data/derisk.db"

[service.model.worker]
host = "127.0.0.1"

# 纯对话模式 - 只配置LLM，不配置embedding模型
[models]
[[models.llms]]
name = "deepseek-r1"
provider = "proxy/deepseek"
api_key = "${env:DEEPSEEK_API_KEY}"

# 注释掉embedding模型配置，避免误调用
# [[models.embeddings]]
# name = "BAAI/bge-large-zh-v1.5"
# provider = "proxy/openai"
# api_url = "https://api.siliconflow.cn/v1/embeddings"
# api_key = "${env:SILICONFLOW_API_KEY}"
